eofficedemo/eofficedemo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls')),
    path('home', include('home.urls')),
    path('nghiphep', include('nghiphep.urls')),
    path('phonghop', include('phonghop.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eofficedemo/home/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'), 
]

eofficedemo/nghiphep/urls.py
from django.urls import path
from . import views
# from .views import PostListView, PostDetailView, home, post, like,dislike, list, AddPost
urlpatterns = [
    path('', views.list, name='blog'),
    path('addpost', views.AddPost, name='addpost'),
    path('editpost/<int:pk>/', views.EditPost, name='editpost'),
#     path('blog', list, name='blog'),
#     # path('<int:id>/', detail, name='post_detail'),
#     path('', home, name='home'),
#     # path('blog', PostListView.as_view(), name='blog'),
    path('<int:pk>/', views.post, name='post_detail'),
    path('like/', views.like, name='likepost'),
    path('dislike/', views.dislike, name='dislikepost'),
]

eofficedemo/nghiphep/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
# class PublishedManager(models.Manager):
#     def get_queryset(self):
#         return super(PublishedManager,self).get_queryset().filter(status='published')
class PostQuerySet(models.QuerySet):
    def get_users_posts(self, username):
        return self.filter(author=username)

class PublishedManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)
    def get_users_posts(self, username):
        return self.get_queryset().get_users_posts(username)
# class PublishedManager(models.Manager):
#     def get_queryset(self):
#         return super(PublishedManager,self).get_queryset().filter(status='draft')
STATUS_CHOICES = (('request', 'Request'),('waiting', 'Waiting'),('approved', 'Approved'),('rejected', 'Rejected'),('canceled', 'Canceled'),)
class Post(models.Model):
    TITLE_CHOICES=(('Nghỉ phép', 'Nghỉ phép'),('Nghỉ không lương', 'Nghỉ không lương'),('Nghỉ ốm', 'Nghỉ ốm'),('Nghỉ sanh', 'Nghỉ sanh'),('Nghỉ hôn nhân', 'Nghỉ hôn nhân'),('Nghỉ tang lễ', 'Nghỉ tang lễ'),('Nghỉ khác', 'Nghỉ khác'),)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='posts')
    title = models.CharField(max_length=100,choices=TITLE_CHOICES,default='Nghỉ phép')
    date_from = models.DateTimeField(default=timezone.now)
    date_end = models.DateTimeField(default=timezone.now)
    numday = models.FloatField(default=1)
    reason = models.TextField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    approval = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='manager')
    approvalbod = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='like', default=None, blank=True)
    like_count = models.BigIntegerField(default='0')
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='request')
    objects = PostQuerySet.as_manager()
    # published = PublishedManager() # Our custom manager
    def __str__(self):
        return self.title
# 'Profile for user {}'.format(self.user.username)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=20)
    date = models.DateTimeField(auto_now_add=True)

    

eofficedemo/nghiphep/forms.py
from django import forms
from .models import Comment, Post
# from .widgets import DatePickerInput, TimePickerInput, DateTimePickerInput


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.author = kwargs.pop('author', None)
        self.post = kwargs.pop('post',None)
        self.body = kwargs.pop('body','')
        self.status = kwargs.pop('status','')
        super().__init__(*args, **kwargs)
    def save(self, commit=True):
        comment=super().save(commit=False)
        comment.author = self.author
        comment.post = self.post
        comment.body = self.body
        comment.status = self.status
        comment.save()
    class Meta:
        model = Comment
        fields = ['body']
        widgets={          
            'body':forms.Textarea(attrs={'class':'form-control form-control-sm', 'rows':'3'}),
        }

class AddPostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        title = forms.CharField(label="Tiêu đề")
        reason = forms.CharField()
        # date_from = forms.CharField(label="Nghỉ từ ngày:")
        date_end = forms.CharField(label="Đến ngày:")
        numday = forms.CharField(label="Số ngày nghỉ:")
        self.author = kwargs.pop('author', None)
        self.approval = kwargs.pop('approval', None)
        self.approvalbod = kwargs.pop('approvalbod', None)
        # self.post = kwargs.pop('post',None)
        super().__init__(*args, **kwargs)
    def save(self, commit=True):
        post=super().save(commit=False)
        post.author=self.author
        post.approval=self.approval
        post.approvalbod=self.approvalbod
        # comment.post = self.post
        post.save()
    class Meta:
        model = Post
        fields = ["date_from","date_end","numday","reason","title",] 
        widgets={          
            'reason':forms.Textarea(attrs={'class':'form-control form-control-sm', 'rows':'2'}),
            'date_from': forms.DateInput(attrs={'class':'form-control form-control-sm','type': 'date'}),
            'date_end': forms.DateInput(attrs={'class':'form-control form-control-sm','type': 'date'}),
            'numday': forms.NumberInput(attrs={'class':'form-control form-control-sm'}),
            'title': forms.Select(attrs={'class':'form-control form-control-sm'})
        }

eofficedemo/nghiphep/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .models import Post
from django.views.generic import ListView, DetailView
from .models import Post, Comment
from members.models import Profile
from .forms import CommentForm, AddPostForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib.auth.models import User
# Create your views here.
def list(request):
    if request.user.profile.phongban.name == 'BGĐ':
        posts = Post.objects.all().filter(approvalbod=request.user)
        pending = Post.objects.all().filter((Q(approval=request.user) & Q(status='request')) | (Q(approvalbod=request.user) & Q(status='waiting')))
        requesting = Post.objects.get_users_posts(request.user).filter(Q(status='request') | Q(status='waiting') | Q(status='rejected'))
        approved = Post.objects.all().filter(approvalbod=request.user).filter(status='approved')
        myApproved = Post.objects.get_users_posts(request.user).filter(status='approved')
        return render(request, 'blog/blog.html', {'Posts':posts, 'Pending':pending, 'Requesting':requesting, 'Approved':approved, 'MyApproved':myApproved})
    elif request.user.profile.phongban.manager == request.user:
        posts = Post.objects.all().filter(approval=request.user)
        pending = Post.objects.all().filter(approval=request.user).filter(status='request')
        requesting = Post.objects.get_users_posts(request.user).filter(Q(status='request') | Q(status='waiting') | Q(status='rejected'))
        approved = Post.objects.all().filter(approval=request.user).filter(status='approved')
        myApproved = Post.objects.get_users_posts(request.user).filter(status='approved')
        return render(request, 'blog/blog.html', {'Posts':posts, 'Pending':pending, 'Requesting':requesting, 'Approved':approved, 'MyApproved':myApproved})
        # return render(request, 'blog/blog.html', {'Posts':posts, 'MyApproved':myApproved, 'Requesting':requesting, 'Pending':pending, 'sumPending':sumPending, 'Approved':approved})
    else:
        posts = Post.objects.get_users_posts(request.user)
        requesting = Post.objects.get_users_posts(request.user).filter(Q(status='request') | Q(status='waiting') | Q(status='rejected'))
        myApproved = Post.objects.get_users_posts(request.user).filter(status='approved')
        # sumPending = str(pending.count())
        return render(request, 'blog/blog.html', {'Posts':posts, 'Requesting':requesting, 'MyApproved':myApproved})
        # return render(request, 'blog/blog.html', {'Posts':posts, 'Pending':pending, 'sumPending':sumPending, 'Approved':approved})

# def detail(request, id):
#     post = Post.objects.get(id = id)
#     return render(request, 'blog/detail.html', {'post': post})

# class PostListView(ListView):
#     model = Post
#     # queryset = Post.objects.all().order_by('date')
#     template_name = 'blog/blog.html'
#     context_object_name = 'Posts'
#     paginate_by = 3
    

# class PostDetailView(DetailView):
#     model = Post
#     template_name = 'blog/detail.html'

def post(request, pk):
    approvallike = False
    post = get_object_or_404(Post, pk=pk)
    form = CommentForm()
    
    if post.likes.filter(pk=post.approval.pk).exists():
        approvallike = True
    # approvalbodlike = post.likes.filter(post.approvalbod)
    # if request.method == 'POST':
    #     form = CommentForm(request.POST, author = request.user, post = post)
    #     if form.is_valid():
    #         form.save()
    #         return HttpResponseRedirect(reverse('post_detail', args=[str(pk)]))
    #         # return HttpResponseRedirect(request.path)
    return render(request, 'blog/detail.html', {'post': post, 'form': form, 'Approvallike': approvallike})

@ login_required
def like(request):
    form = CommentForm()
    if request.POST.get('action') == 'post':
        result = ''
        remove = False
        pk = request.POST.get('postid')
        post = get_object_or_404(Post, pk=pk)
        body = request.POST.get('contentbody')
        userid = post.author.profile.id
        profile = get_object_or_404(Profile, pk=userid)
        if request.user == post.author:
            form = CommentForm(request.POST, author = request.user, post = post, body=body, status='Đã cập nhật')
            post.status='request'
            post.save()
            form.save()
        elif post.approval == post.approvalbod:
            form = CommentForm(request.POST, author = request.user, post = post, body=body, status='Đã duyệt')
            post.likes.add(request.user)
            post.status='approved'
            post.like_count += 1
            result = post.like_count
            profile.songaynghiphep += post.numday
            if profile.sophepnam >= profile.songaynghiphep:
                profile.songaynghiphepconlai = profile.sophepnam - profile.songaynghiphep
            else:
                profile.songaynghiphepconlai = 0
                profile.songaynghikhongphep = profile.songaynghiphep - profile.sophepnam
            profile.save()
            post.save()
            form.save()
        else:
            form = CommentForm(request.POST, author = request.user, post = post, body=body, status='Đã duyệt')
            if post.numday < 3:
                if request.user == post.approval:
                    if post.likes.filter(pk=request.user.pk).exists():
                        # post.likes.remove(request.user)
                        # post.like_count -= 1
                        result = post.like_count
                        # remove = True
                        post.save()
                        form.save()
                    else:
                        post.likes.add(request.user)
                        post.status='approved'
                        post.like_count += 1
                        result = post.like_count
                        profile.songaynghiphep += post.numday
                        if profile.sophepnam >= profile.songaynghiphep:
                            profile.songaynghiphepconlai = profile.sophepnam - profile.songaynghiphep
                        else:
                            profile.songaynghiphepconlai = 0
                            profile.songaynghikhongphep = profile.songaynghiphep - profile.sophepnam
                        profile.save()
                        post.save()
                        form.save()
            else:
                if request.user == post.approval:
                    if post.likes.filter(pk=request.user.pk).exists():
                        # post.likes.remove(request.user)
                        # post.like_count -= 1
                        result = post.like_count
                        # remove = True
                        post.save()
                        form.save()
                    else:
                        post.likes.add(request.user)
                        post.status='waiting'
                        post.like_count += 1
                        result = post.like_count
                        post.save()
                        form.save()
                if request.user == post.approvalbod:
                    if post.likes.filter(pk=request.user.pk).exists():
                        # post.likes.remove(request.user)
                        # post.like_count -= 1
                        result = post.like_count
                        # remove = True
                        post.save()
                        form.save()
                    else:
                        post.likes.add(request.user)
                        post.status='approved'
                        post.like_count += 1
                        result = post.like_count
                        profile.songaynghiphep += post.numday
                        if profile.sophepnam >= profile.songaynghiphep:
                            profile.songaynghiphepconlai = profile.sophepnam - profile.songaynghiphep
                        else:
                            profile.songaynghiphepconlai = 0
                            profile.songaynghikhongphep = profile.songaynghiphep - profile.sophepnam
                        profile.save()
                        post.save()
                        form.save()

        return render(request, 'blog/detail.html', {'post': post, 'form': form})

@ login_required
def dislike(request):
    form = CommentForm()
    if request.POST.get('action') == 'post':
        result = ''
        remove = False
        pk = request.POST.get('postid')
        post = get_object_or_404(Post, pk=pk)
        body = request.POST.get('contentbody')
        if request.user == post.author:
            form = CommentForm(request.POST, author = request.user, post = post, body=body, status='Hủy')
            if post.likes.filter(pk=request.user.pk).exists():
                post.likes.remove(request.user)
                post.like_count = 0
                post.status='canceled'
                result = post.like_count
                remove = True
                post.save()
                form.save()
            else:
                # post.likes.add(request.user)
                # post.like_count += 1
                
                post.like_count = 0
                post.status='canceled'
                result = post.like_count
                post.save()
                form.save()
        else:
            form = CommentForm(request.POST, author = request.user, post = post, body=body, status='Trả về')
            if post.likes.filter(pk=request.user.pk).exists():
                post.likes.remove(request.user)
                post.like_count = 0
                post.status='rejected'
                result = post.like_count
                remove = True
                post.save()

eofficedemo/nghiphep/templates/blog/addpost.html
{% extends "base.html" %}

{% block title %}Tạo đơn xin nghỉ phép{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <h3><center>Tạo đơn xin nghỉ phép</center></h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="container">
        
                <div class="card">
                  </br>
                    
                  <div class="row">
          
                    <div class="col-sm-1">
                    </div>
          
                    <div class="col-sm-10">
                      <div class="row">
                        <div class="col-sm-3">
                          <img src="/media/logo.png" class="responsive-img" style="max-height:100px;max-width:100px; padding:5px">
                        </div>
                        <div class="col-sm-8">
                          
                          <h6>ĐƠN XIN NGHỈ PHÉP</h6>
                          <small><small>Bộ phận: {{request.user.profile.phongban.name}}</small></small></br>
                          {% comment %} <small><small>Ngày viết đơn: <a class="text-danger">{{form.date|date:"d/m/Y"}}</a></small></small> {% endcomment %}
                          
                        </div>
          
                        <div class="col-sm-1">
                        </div>
          
                      </div>
                    </div>
                    <div class="col-sm-1">
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-1">
                    </div>
          
                    <div class="col-sm-10">
                      
                      <small><small>
                        <div class="mb-1 row">
                          <label for="statichovaten" class="col-sm-3 col-form-label">Họ và tên:</label>
                          <div class="col-sm-4">
                            <input class="form-control form-control-sm" type="text" value="{{request.user.last_name}} {{request.user.first_name}}" aria-label="readonly input example" readonly>
                          </div>
                          <label for="staticmsnv" class="col-sm-1 col-form-label"></label>
                          <label for="staticmsnv" class="col-sm-2 col-form-label">MSNV:</label>
                          <div class="col-sm-2">
                            <input class="form-control form-control-sm" type="text" value="VTC-{{request.user.profile.msnv}}" aria-label="readonly input example" readonly>
                          </div>
                        </div>
                      </small></small>
                      <small><small>
                        <div class="mb-1 row">
                          <label for="statichovaten" class="col-sm-3 col-form-label">Phép năm:</label>
                          <div class="col-sm-3">
                            <input class="form-control form-control-sm" type="text" value="{{request.user.profile.sophepnam}}" aria-label="readonly input example" readonly>
                          </div>
                          
                          <label for="staticmsnv" class="col-sm-1 col-form-label"></label>
                          <label for="staticmsnv" class="col-sm-3 col-form-label">Số ngày đã nghỉ:</label>
                          <div class="col-sm-2">
                            <input class="form-control form-control-sm" type="text" value="{{request.user.profile.songaynghiphep}}" aria-label="readonly input example" readonly>
                          </div>
                        </div>
                      </small></small>
                      <small><small>
                        <div class="mb-1 row">
                          <label for="staticmsnv" class="col-sm-3 col-form-label">Số ngày phép còn lại:</label>
                          <div class="col-sm-3">
                            <input class="form-control form-control-sm" type="text" value="{{request.user.profile.songaynghiphepconlai}}" aria-label="readonly input example" readonly>
                          </div>
                        </div>
                      </small></small>
                      <small><small>
                        <div class="mb-1 row">
                          <label for="staticmsnv" class="col-sm-3 col-form-label">Nghỉ từ ngày:</label>
                          <div class="col-sm-3" id = "dateinput">
                            {{form.date_from}}
                          </div>
                          <label for="staticmsnv" class="col-sm-1 col-form-label"></label>
                          <label for="staticmsnv" class="col-sm-2 col-form-label">Đến ngày:</label>
                          <div class="col-sm-3">
                            {{form.date_end}}
                          </div>
                        </div>
                      </small></small>

                      

                      <small><small>
                        <div class="mb-1 row">
                          <label for="staticmsnv" class="col-sm-3 col-form-label">Số ngày nghỉ:</label>
                          <div class="col-sm-3">
                            {{form.numday}}
                          </div>
                        </div>
                      </small></small>
                      <small><small>
                        <div class="mb-1 row">
                          <label for="staticmsnv" class="col-sm-3 col-form-label">Lý do xin nghỉ:</label>
                          <div class="col-sm-6">
                            {{form.reason}}
                          </div>
                        </div>
                      </small></small>
                      <small><small>
                        <div class="mb-1 row">
                          <label for="staticmsnv" class="col-sm-3 col-form-label">Điện thoại liên hệ:</label>
                          <div class="col-sm-6">
                            <input class="form-control form-control-sm" rows="3" type="text" value="{{request.user.profile.phone}}" aria-label="readonly input example" readonly>
                          </div>
                        </div>
                      </small></small>
                      <small><small>
                        <div class="mb-1 row">
                          <label for="staticmsnv" class="col-sm-3 col-form-label">Loại nghỉ phép</label>
                          <div class="col-sm-6">
                            {{form.title}}
                          </div>
                        </div>
                      </small></small>
                      
                    
                    </div>
                    <div class="col-sm-1">
                    </div>
                  </div>
                  </br>
                </div>
                
                </br>
                
              </div>
            
            <center><button class="btn btn-secondary btn-sm">Gửi duyệt</button></center>
        </form>
    {% else %}
        You are not allowed here!
    {% endif %}
{% endblock %}

{% block javascript %}

<script>
    
    
  </script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).on('change', '#id_date_from', function (e) {
    
        
        let datefrom = new Date(document.querySelector("#id_date_from").value).getTime();
        let dateend = new Date(document.querySelector("#id_date_end").value).getTime();
        let num = Math.ceil((dateend - datefrom) / (24*60*60*1000));
        
        document.querySelector("#id_numday").value = num + 1
        
        
    })
    $(document).on('change', '#id_date_end', function (e) {
    
        
        let datefrom = new Date(document.querySelector("#id_date_from").value).getTime();
        let dateend = new Date(document.querySelector("#id_date_end").value).getTime();
        let num = Math.ceil((dateend - datefrom) / (24*60*60*1000));
        
        document.querySelector("#id_numday").value = num + 1
        
        
        
    })
</script>
{% endblock javascript %}